services:
  api:
    container_name: go-gin-d-api
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    ports:
      - "8080:8080"
      - "8081:8081"
    tty: true
    stdin_open: true
