services:
  api:
    container_name: go-gin-d-api
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    env_file:
      - ./.env
    command: air -c .air.toml
    volumes:
      - ./src:/go/src
    tty: true
    stdin_open: true
    ports:
      - 8080:8080